/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  manage_config: () => import("@/views/manage/config/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  message_list: () => import("@/views/message/list/index.vue"),
  requirement_detail: () => import("@/views/requirement/detail/[id].vue"),
  requirement_list: () => import("@/views/requirement/list/index.vue"),
  "requirement_task-detail": () => import("@/views/requirement/task-detail/[id].vue"),
  "requirement_task-list": () => import("@/views/requirement/task-list/index.vue"),
  team_members: () => import("@/views/team/members/index.vue"),
  team_workload: () => import("@/views/team/workload/index.vue"),
  templates_projects: () => import("@/views/templates/projects/index.vue"),
  templates_tasks: () => import("@/views/templates/tasks/index.vue"),
};
