/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'mdi:cog',
      order: 2
    },
    children: [
      {
        name: 'manage_config',
        path: '/manage/config',
        component: 'view.manage_config',
        meta: {
          title: 'manage_config',
          i18nKey: 'route.manage_config',
          icon: 'mdi:cog-outline'
        }
      }
    ]
  },
  {
    name: 'requirement',
    path: '/requirement',
    component: 'layout.base',
    meta: {
      title: 'requirement',
      i18nKey: 'route.requirement',
      icon: 'mdi:file-document-outline',
      order: 1
    },
    children: [
      {
        name: 'requirement_detail',
        path: '/requirement/detail/:id',
        component: 'view.requirement_detail',
        props: true,
        meta: {
          title: 'requirement_detail',
          i18nKey: 'route.requirement_detail',
          hideInMenu: true,
          order: 2
        }
      },
      {
        name: 'requirement_list',
        path: '/requirement/list',
        component: 'view.requirement_list',
        meta: {
          title: 'requirement_list',
          i18nKey: 'route.requirement_list',
          icon: 'mdi:format-list-bulleted',
          order: 1
        }
      },
      {
        name: 'requirement_task-detail',
        path: '/requirement/task-detail/:id',
        component: 'view.requirement_task-detail',
        meta: {
          title: 'requirement_task-detail',
          i18nKey: 'route.requirement_task-detail',
          hideInMenu: true
        }
      },
      {
        name: 'requirement_task-list',
        path: '/requirement/task-list',
        component: 'view.requirement_task-list',
        meta: {
          title: 'requirement_task-list',
          i18nKey: 'route.requirement_task-list',
          icon: 'mdi:clipboard-list',
          order: 2
        }
      }
    ]
  }
];
